# "desired_plates":
#  - "172"
#  - "173"
#  - "174"
#  - "175"
#  - "176"
#  - "177"
#  - "178"
#  - "179"
#  - "180"
#  - "181"
#  - "182"
#  - "183"
#  - "184"
#  - "185"
#  - "186"
#  - "187"
#  - "188"
#  - "189"
#  - "190"
#  - "191"
#  - "192"
#  - "193"
#  - "194"
#  - "195"
#  - "196"
#  - "197"
#  - "198"
#  - "199"
#  - "200"
#  - "201"
#  - "202"
#  - "203"
#  - "204"
#  - "205"
#  - "206"
#  - "207"
#  - "208"
#  - "209"
#  - "210"
#  - "211"
#  - "212"
#  - "213"
#  - "214"
#  - "215"
#  - "216"
#  - "217"
#  - "218"
#  - "219"
#  - "220"
#  - "221"
#  - "222"
#  - "223"
#  - "224"
#  - "225"
#  - "226"
#  - "227"
#  - "228"
#  - "229"
#  - "230"
#  - "231"
#  - "232"
#  - "233"
#  - "234"
#  - "235"
#  - "236"
#  - "237"
#  - "238"
#  - "239"
#  - "240"
#  - "241"
#  - "242"
#  - "257"
"assume_dates_present": false
"default": "not applicable"
"study_start_date": "10/21/2008"
"locations":
  "sandiego":
    "metadata_fields":
      "elevation": 193
      "geo_loc_name": "USA:CA:San Diego"
      "latitude": 32.84
      "longitude": -117.25
  "boulder":
    "metadata_fields":
      "elevation": 1624.1
      "geo_loc_name": "USA:CO:Boulder"
      "latitude": 40.1
      "longitude": -105.2
"metadata_fields":
  "sample_name": null
#  "host_subject_id": null
#  "collection_timestamp": null
#  "days_since_first_day": null
#  "description": null
#  "dna_extracted": true
#  "elevation": null
#  "empo_1": null
#  "empo_2": null
#  "empo_3": null
#  "empo_4": null
#  "env_biome": "urban biome"
#  "env_feature": null
#  "env_material": null
#  "env_package": null
#  "geo_loc_name": null
#  "host_age": null
#  "host_age_units": null
#  "host_body_habitat": null
#  "host_body_mass_index": null
#  "host_body_product": null
#  "host_body_site": null
#  "host_common_name": null
#  "host_height": null
#  "host_height_units": "cm"
#  "host_nation": null
#  "host_scientific_name": null
#  "host_taxid": null
#  "host_weight": null
#  "host_weight_units": "kg"
#  "is_collection_timestamp_valid": null
#  "latitude": null
#  "life_stage": null
#  "longitude": null
#  "m03_age_years": null
#  "mapping_file_name": "leaveblank"
#  "notes": "leaveblank"
#  "ordinal_timestamp": null
#  "original_collection_timestamp": null
#  "physical_specimen_location": "UCSDMI"
#  "physical_specimen_remaining": false
#  "public": true
#  "qiita_study_id": 11052
#  "sample_type": null
#  "sample_type_qiita": null
#  "scientific_name": null
#  "sex": null
#  "single_double_swab_test": "leaveblank"
#  "taxon_id": null
#  "title": "ABTX"
"host_type_specific_metadata":
  "human":
    "metadata_fields":
      "empo_1": "Host-associated"
      "empo_2": "Host-associated (non-saline)"
      "empo_3": "Animal (non-saline)"
      "env_feature": "human-associated habitat"
      "host_common_name": "human"
      "host_scientific_name": "Homo sapiens"
      "host_taxid": 9606
    "sample_type_specific_metadata":
      "br":
        "metadata_fields":
          "description": "breast"
          "empo_4": "Animal surface (non-saline)"
          "env_material": "sebum"
          "env_package": "human-skin"
          "host_body_habitat": "UBERON:skin"
          "host_body_product": "UBERON:sebum"
          "host_body_site": "UBERON:breast"
          "sample_type": "skin"
          "sample_type_qiita": "skin of breast"
          "scientific_name": "human skin metagenome"
          "taxon_id": 539655
      "fe":
        "metadata_fields":
          "description": "stool"
          "empo_4": "Animal distal gut (non-saline)"
          "env_material": "feces"
          "env_package": "human-gut"
          "host_body_habitat": "UBERON:feces"
          "host_body_product": "UBERON:feces"
          "host_body_site": "UBERON:feces"
          "sample_type": "feces"
          "sample_type_qiita": "feces"
          "scientific_name": "human gut metagenome"
          "taxon_id": 408170
      "st":
        "alias": "fe"
      "fh":
        "metadata_fields":
          "description": "skin of forehead"
          "empo_4": "Animal surface (non-saline)"
          "env_material": "sebum"
          "env_package": "human-skin"
          "host_body_habitat": "UBERON:skin"
          "host_body_product": "UBERON:sebum"
          "host_body_site": "UBERON:skin of forehead"
          "sample_type": "skin"
          "sample_type_qiita": "skin of head"
          "scientific_name": "human skin metagenome"
          "taxon_id": 539655
      "frh":
        "alias": "fh"
      "fha":
        "alias": "fh"
      "fhb":
        "alias": "fh"
      "lh":
        "metadata_fields":
          "description": "skin of left hand"
          "empo_4": "Animal surface (non-saline)"
          "env_material": "sebum"
          "env_package": "human-skin"
          "host_body_habitat": "UBERON:skin"
          "host_body_product": "UBERON:sebum"
          "host_body_site": "UBERON:skin of hand"
          "sample_type": "skin"
          "sample_type_qiita": "skin of hand"
          "scientific_name": "human skin metagenome"
          "taxon_id": 539655
      "lp":
        "alias": "lh"
      "lpalm":
        "alias": "lh"
      "lha":
        "alias": "lh"
      "lhb":
        "alias": "lh"
      "rh":
        "metadata_fields":
          "description": "skin of right hand"
          "empo_4": "Animal surface (non-saline)"
          "env_material": "sebum"
          "env_package": "human-skin"
          "host_body_habitat": "UBERON:skin"
          "host_body_product": "UBERON:sebum"
          "host_body_site": "UBERON:skin of hand"
          "sample_type": "skin"
          "sample_type_qiita": "skin of hand"
          "scientific_name": "human skin metagenome"
          "taxon_id": 539655
      "rp":
        "alias": "rh"
      "rha":
        "alias": "rh"
      "rhb":
        "alias": "rh"
      "t":
        "metadata_fields":
          "description": "saliva"
          "empo_4": "Animal secretion (non-saline)"
          "env_material": "saliva"
          "env_package": "human-oral"
          "host_body_habitat": "UBERON:oral cavity"
          "host_body_product": "UBERON:saliva"
          "host_body_site": "UBERON:tongue"
          "sample_type": "tongue"
          "sample_type_qiita": "tongue"
          "scientific_name": "human oral metagenome"
          "taxon_id": 447426
      "ta":
        "alias": "t"
      "tb":
        "alias": "t"
  "blank":
    "default_value": "not applicable"
    "sample_type_specific_metadata":
      "blank":
        "metadata_fields":
          "empo_1": "Control"
          "empo_2": "Negative"
          "empo_3": "Sterile water blank"
          "empo_4": "Sterile water blank"
          "env_feature": "research facility"
          "env_material": "sterile water"
          "env_package": "misc environment"
          "host_age_units": "years"
          "is_collection_timestamp_valid": false
          "sample_type": "control blank"
          "sample_type_qiita": "control blank"
          "scientific_name": "metagenome"
          "taxon_id": 256318
"host_specific_metadata":
  "rk":
    "host_common_name": "human"
    "default_value": "not provided"
    "date_of_birth": "11/13/1976"
    "location_break":
      "before_location": "boulder"
      "after_location": "sandiego"
      "after_start_date": "01/01/2015"
    "metadata_fields":
      "host_subject_id": "M03"
      "host_age_units": "years"
      "host_height": 165
      "host_nation": "New Zealand"
      "host_weight_units": "kg"
      "life_stage": "adult"
      "sex": "male"
  "blank":
    "host_common_name": "blank"
    "location": "sandiego"
"metadata_transformers":
  "pre_population":
    "host_age":
      "source": "age"
      "function": "pass_through"

