"default": "not applicable"
"study_start_date": "10/21/2008"
"study_specific_fields":
  "host_type_specific_metadata":
    ebi_submittable:
      metadata_fields:
        country:
          allowed:
            - "USA"
          default: "USA"
          type: string
        dna_extracted:
          allowed:
            - 'TRUE'
          default: 'TRUE'
          type: string
        title:
          default: "NPH"
          type: string
    "human":
      "metadata_fields":
        elevation:
          default: 0
          type: number
        geo_loc_name:
          allowed:
            - 'USA'
          default: 'USA'
          type: string
        host_height:
          allowed:
            - "not provided"
          default: "not provided"
          type: string
        host_weight:
          allowed:
            - "not provided"
          default: "not provided"
          type: string
        latitude:
          default: 40
          type: number
        longitude:
          default: -100
          type: number
        physical_specimen_location:
          allowed:
            - 'UCSD'
          default: "UCSD"
          type: string
        physical_specimen_remaining:
          allowed:
            - 'TRUE'
          default: 'TRUE'
          type: string
      "sample_type_specific_metadata":
        "feces":
          "metadata_fields":
            description:
              allowed:
                - "fecal sample"
              default: "fecal sample"
              type: string
            qiita_sample_type:
              allowed:
                - "feces"
              default: "feces"
              empty: false
              is_phi: false
              required: false
              type: string
    "control":
      "default_value": "not applicable"
      "sample_type_specific_metadata":
        "shield blank":
          "metadata_fields":
            qiita_sample_type:
              allowed:
                - "control shield"
              default: "control shield"
              empty: false
              is_phi: false
              required: false
              type: string
"metadata_transformers":
  "pre_population":
    collection_date:
      sources:
        - "collection_date_time"
      function: "format_a_datetime"
    collection_timestamp:
      sources:
        - "collection_date_time"
      function: "format_a_datetime"
    "host_age":
      "sources":
        - "age"
      "function": "pass_through"
    host_body_mass_index:
      sources:
        - "bmi"
      function: "pass_through"
    host_life_stage:
      sources:
        - "age"
      function: "transform_age_to_life_stage"
    host_subject_id:
      sources:
        - "biobank_id"
      function: "pass_through"
    sex:
      sources:
        - "sex_at_birth"
      function: "transform_sex_at_birth_to_sex"
    tube_id:
      sources:
        - "matrix_id"
      function: "pass_through"

